CREATE TABLE PERSON (
	ID INT AUTO_INCREMENT NOT NULL,
	`FIRSTNAME` VARCHAR(100) NOT NULL,
    `LASTNAME` VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100),
    CITY VARCHAR(100),
    PRIMARY KEY(ID)
);